FROM node:16-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM alpine:latest
RUN apk update && apk add --no-cache ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/one-api .
EXPOSE 3000
ENTRYPOINT ["./one-api"]
